### ISSUE TITLE
how is versionioning handled in this structure ? 

### ISSUE THREAD

**Issue by priya-gitTest** [zhanymkanov/fastapi-best-practices#10]
Is it just by Git or you also handle with via API route ?

**Comment by zhanymkanov** [comment]
Hey @priya-gitTest 

Sorry for the long delay, I planned a more detailed answer but had no time to make it published.

In short, we do versioning in URL with API version prefix, but I wouldn't say I love the approach we did.

For fast releases of breaking API changes, we would just add a sibling endpoint with a v2 prefix. Ideally, it would be two independent deployments, but when CI CD is not perfect, which is usual for startups, you add some imperfections.

I guess, there is no best practice in the versioning thing, but a proper choice considering your business requirements and characteristics of your infra.
