### ISSUE TITLE
Need for a template

### ISSUE THREAD

**Issue by akpan-daniel** [zhanymkanov/fastapi-best-practices#13]
IMO, there is a need for a starter template to get accustomed to these practice or for better reference. Not compulsory, just my personal opinion.

**Comment by akpan-daniel** [comment]
That would be great. That solves this issue, should I leave this open till the article is posted or close?

**Comment by zhanymkanov** [comment]
Let's keep it open, that's ok

**Comment by zhanymkanov** [comment]
Here it is: https://github.com/zhanymkanov/fastapi_production_template

Article will arrive in a few days
