### ISSUE TITLE
why dispatch using src/dispatch/ as highest level of app

### ISSUE THREAD

**Issue by Shiyinq** [zhanymkanov/fastapi-best-practices#16]
in this repo the highest level of app is `src/`

```
fast-api-project/
└── src/
    ├── domain1
    └── domain2
```

and then i see the Dispatch repo that mention on the description
highest level of app is `src/distpatch/`

```
dispatch/
└── src/
    └── dispatch/
        ├── domain1
        └── domain2

```
dispatch folder inside src is called domain to?
what should i choose?

**Comment by zhanymkanov** [comment]
It's really up to you actually. 

If you stick to the structure in the best practices, you can run code as is and do no configurations in env or `package_dir`, while their way of accessing packages requires some modifications. You can see that in the code, they import files like `from dispatch.database.core` though their actual structure slightly differs.

If you use `setuptools`, maybe you might want a structure like theirs, but I don't know tbh. I never tried running web apps that way.
