### ISSUE TITLE
Handling the nested response

### ISSUE THREAD

**Issue by allmonday** [zhanymkanov/fastapi-best-practices#20]
Hey, this article is fantastic and inspired a lot to me, appreciate!

for No.19:  https://github.com/zhanymkanov/fastapi-best-practices#19-sql-first-pydantic-second,  I have some attempts.

Recently I'm working on a small toolkit to handle the nested part.  

**TLDR**: https://github.com/allmonday/pydantic_resolve#demo-2-integrated-with-aiodataloader

We use GraphQL in our project, which is very flexible and allows for easy definition of new fields. When combined with dataloader, it can solve the potential N+1 query problem. 

However, as an internal API entry, I feel that GraphQL is too flexible. FastAPI's JSON schema, combined with various client-codegen tools, can reduce a lot of front-end and back-end workload, such as type definitions in front-end.

codegen: https://fastapi.tiangolo.com/advanced/generate-clients/

Therefore, I thought of leveraging the advantages of dataloader and Pydantic:

Pydantic can provide schema, while dataloader can solve the N+1 problem for nested field queries.

```python
        BOOKS_DB = {
            1: [{'name': 'book1'}, {'name': 'book2'}],
            2: [{'name': 'book3'}, {'name': 'book4'}],
        }

        class Book(BaseModel):
            name: str

        class BookLoader(DataLoader):
            async def batch_load_fn(self, keys):
                books = [[Book(**bb) for bb in BOOKS_DB .get(k, [])] for k in keys]
                return books

        book_loader = BookLoader()  

        class Student(BaseModel):
            id: int
            name: str

            books: Tuple[Book, ...] = tuple()
            def resolve_books(self):
                return book_loader.load(self.id)

        # usage
        students = [Student(id=1, name="jack"), Student(id=2, name="mike")]
        results = await resolve(students)
```

By this way it also simplify the SQL part by moving the nested part into query in loader.

And another bonus is you can reuse the loader anywhere.

**Comment by allmonday** [comment]
for more detail usage, please refer to this demo repository: https://github.com/allmonday/stormtrooper

**Comment by zhanymkanov** [comment]
Hey,

Thank you for your kind words, I'm happy it inspired you for some things!

Your project looks interesting, though I am not sure I fully understand it. I like the idea of hiding the complex data transformation in pydantic schemas. Also, I'm curious how would the code above solve the N+1 problem, since it looks like an array of repetitive DB calls, which is exactly an N+1. 

If your proposal is to retrieve some extra data from storage within Pydantic models, then I'm not a fan of it. I believe it's a popular opinion to keep Pydantic models for data validation only, not for data extraction.

**Comment by allmonday** [comment]
hi, 

At first, I use ORM's relationship and pydantic `orm_mode` to handle the nested response ( https://fastapi.tiangolo.com/tutorial/sql-databases/#create-initial-pydantic-models-schemas), and gradually, I find this way is too heavy, pydantic models and ORM models are kind of coupled with each other.

In my scenario (a project management too), I need to generate some deep-nested structure such as a structure from story -> tasks -> developers.

sample:
```json
[
    {
        "id": 1,
        "name": "story-1", 
        "tasks": [
            {
                "id": 1,
                "name": "task-1", 
                "developers": [
                    {
                        "id": 1,
                        "name": "dev-1"
                    }
                    {
                        "id": 2,
                        "name": "dev-2"
                    }
                ]
            }
        ]
    }
]
```

If using pure SQL alone, this will need quite a lot `group by conditions` and sometimes need the help from pandas to generate nested structure. 


> Also, I'm curious how would the code above solve the N+1 problem, since it looks like an array of repetitive DB calls, which is exactly an N+1.

this is the feature provided by https://github.com/syrusakbary/aiodataloader, this tool can collect keys and execute the query in next tick. 

take it for example, assuming I have got a list of Tasks `[{name: 'task-1', id:1}, {name: 'task-2', id: 2}, { name: 'task-3', id:3}]` then I want to find related comment objects.

```python
def resolve_comments(self):
        return loader.dataloader_context.get()['task']['default'].load(self.id)
```

`resolve_comment` will return Future object, at this moment, nothing will happen, the real query will trigger after all Tasks being iterated (so task_ids will be [1,2,3]).

```python
class CommentLoader(DataLoader):
    async def batch_load_fn(self, task_ids):
        async with async_session() as session, session.begin():

            res = await session.execute(
                select(models.Comment).filter(models.Comment.task_id.in_(task_ids))
                )
            rows = res.scalars().all()

            dct = defaultdict(list)
            for row in rows:
                dct[row.task_id].append(model_schema.Comment.from_orm(row))
            return [dct.get(k, []) for k in task_ids]
```
`batch_load_fn` will be executed, so that there will be only 1 query happened. then `aiodataloader` and `pydantic-resolve` will take care of the rest part of work.

If I need to create `story -> tasks -> developers` , it will just take another 2 extra query to get the tasks and developers.


> If your proposal is to retrieve some extra data from storage within Pydantic models, then I'm not a fan of it.

you are right,  just like No.22 says returning a pydantic object is a bit waste of performance.  but I find it still have some value to use it during service calculation, for example.  it can validate in early stage of service logic

maybe dataclass is a better choice during service part.  `pydantic-resolve` support it too.  https://github.com/allmonday/pydantic-resolve/blob/master/tests/test_resolver.py#L55

**Comment by allmonday** [comment]
I committed a new test : https://github.com/allmonday/pydantic-resolve/blob/master/tests/test_with_sqlite.py
The last two asserts ensures that the batch query will only be executed once for each level.

**Comment by mvandermeulen** [comment]
> for more detail usage, please refer to this demo repository: https://github.com/allmonday/stormtrooper
> 
> * https://github.com/allmonday/stormtrooper/blob/main/backend/app/entries/task/schema.py
> * https://github.com/allmonday/stormtrooper/blob/main/backend/app/entries/task/loader.py
> * https://github.com/allmonday/stormtrooper/blob/main/backend/app/middleware/loader.py

@allmonday thanks for outlining what you are working on, this repo contains lots of valuable resources and I've very much enjoyed reading everyones contributions. I was hoping to check out your demo repository to gain a greater understanding of the solution you are proposing but the repository no longer exists. Do you still recommend this method or would I be better off focusing on evaluating other solutions?

**Comment by allmonday** [comment]
@mvandermeulen, thank you!
I've set stormtrooper repo as private, so the link is no longer available. 
in fact, in latest version, you don't need to initialize loader in middleware anymore. 

and you can still view the `examples folder` which are up to date:
this link shows all features `pydantic-resolve` can provide.
https://github.com/allmonday/pydantic-resolve/blob/master/examples/6_sqlalchemy_loaderdepend_global_filter.py
