### ISSUE TITLE
Better sqla core

### ISSUE THREAD

**Issue by sayanarijit** [zhanymkanov/fastapi-best-practices#21]
Since you are using sqlalchemy core to make raw sql queries, you might like to use a more maintainable approach to declare and use the tables and columns. ORMs aren't very flexible, but a huge help for type driven development. For example using `obj.column` is more maintainable than using `table.c.column`, since the latter is dynamic, and lack type hints.

We can take the middle ground by re-declaring the columns like `column = table.c.column`, and using the redeclared version everywhere. But that will add a lot of boilerplate code.

One way to avoid boilerplate code is using a factory class like in https://github.com/sayanarijit/sqla-fancy-core which lets us declare the columns almost the same way we declare in the orms, but without the orm magic.

We can also subclass the factory to create custom column type like:

```python
from sqla_fancy_core import TableFactory as _TableFactory

class TableFactory(_TableFactory):
    def col(self, *args, nullable=False, **kwargs):
        kwargs["nullable"] = nullable
        return super().col(*args, **kwargs)

    def foreign_key(
        self,
        name: str,
        ref: str | sa.Column,
        *args,
        onupdate="CASCADE",
        ondelete="CASCADE",
        **kwargs
    ):
        fk = sa.ForeignKey(ref, onupdate=onupdate, ondelete=ondelete)
        return self.col(name, fk, *args, **kwargs)

    def name(self, *args, **kwargs):
        return self.string("name", *args, **kwargs)

    def slug(self, *args, **kwargs):
        return self.text("slug", *args, **kwargs)
```

**Comment by zhanymkanov** [comment]
Looks interesting! I like the idea and the simplicity of the solution.
