### ISSUE TITLE
Questions about 3. Use Dependencies data valadation vs DB

### ISSUE THREAD

**Issue by Jim0530** [zhanymkanov/fastapi-best-practices#27]
```
async def valid_post_id(post_id: UUID4) -> Mapping:
    post = await service.get_by_id(post_id)
    if not post:
        raise PostNotFound()

    return post
```
How should service be written, my question is how to maintain session when you don't put session into dependencies? Is there a way to put session and valid data into same dependencies?

**Comment by Jim0530** [comment]
i mean if i do sqlalchemy in a async way, how should i initiate a service object?

**Comment by Jim0530** [comment]
if i have a validate function:
validate function
`async def validate_test_execut_data(
    session: AsyncSession, data: DataModels
) -> DataModels:
    service = CRUD(session)
    results = await service.check(data)
    if results is None:....`
and my router usually will be
```
@app.post
async def post_function(session : AyncSession = Depends(get_db_session))
```
How can i combine these two with one dependencies, to make use of dependencies?? Thanks, I've been recently studying fastapi, this makes me confused.

**Comment by zhanymkanov** [comment]
If you usually retrieve db_session with dependency, then you should do the same within the `validate_test_execut_data` dependency, i.e. 
```python3
async def validate_test_execut_data(session: AsyncSession = Depends(get_db_session), data: DataModels) -> DataModels:
    service = CRUD(session)
    results = await service.check(data)
    if results is None:....
```

**Comment by Jim0530** [comment]
```
async def validate_test_execut_data(session: AsyncSession = Depends(get_db_session), data: DataModels) -> DataModels:
    service = CRUD(session)
    results = await service.check(data)
    if results is None:....
```
so will it work like down below?
```
@app.post
async def post_function(results: DataModels = Depends(validate_test_execut_data)):
```

**Comment by Jim0530** [comment]
It works,Really Appreciate. However is this the best way to do?? Is there any other tricks to control the session? What should i read to strengthen these fastapi & sqlalchemy knowledge??

**Comment by zhanymkanov** [comment]
The best thing you can do is to read the docs :)
