### ISSUE TITLE
Use `run_in_threadpool` or not?

### ISSUE THREAD

**Issue by hmbui-noze** [zhanymkanov/fastapi-best-practices#32]
Thank you again for this useful repo.
I have a question regarding your tip [23](https://github.com/zhanymkanov/fastapi-best-practices#23-if-you-must-use-sync-sdk-then-run-it-in-a-thread-pool). I wonder what the differences between using `def` function and `run_in_threadpool` in `async` function. They works the same way to my knowledge. My use case is that I'm using `google_storage_python` to download file from GCS but it's a blocking I/O library

**Comment by simjak** [comment]
@hmbui-noze  I can recommend an amazing book about Async programming, the code examples are based on Rust, but the principles can applied to any programming language:
[Asynchronous Programming in Rust](https://www.amazon.com/Asynchronous-Programming-Rust-asynchronous-programming/dp/1805128132)
Discussion page:
https://www.reddit.com/r/rust/comments/1amlro1/new_rust_book_asynchronous_programming_in_rust_is/

**Comment by zhanymkanov** [comment]
In tip 23, `run_in_threadpool` is useful, when you can't use `def` router, i.e. you have other `async` parts.
