### ISSUE TITLE
Pydantic 2+

### ISSUE THREAD

**Issue by ckpinguin** [zhanymkanov/fastapi-best-practices#33]
Is it possible to update [8](https://github.com/zhanymkanov/fastapi-best-practices#8-custom-base-model-from-day-0) to use pydantic 2+? I'm not pro enough to figure out the migration path for that.

**Comment by zhanymkanov** [comment]
Sure, I was planning to do that in upcoming weeks, but guess I will do it this week

**Comment by zhanymkanov** [comment]
Done
