### ISSUE TITLE
Could you recommend an actual project that employs this project structure?

### ISSUE THREAD

**Issue by yejue** [zhanymkanov/fastapi-best-practices#40]
I'm eager to explore the overall arrangement in practical application. Primarily, I'm interested in examining the logical separation of dependencies and services. For instance, while working on the login functionality, I placed JWT within utils and encapsulated user-related operations within a service class, such as get_current_user. However, later on, I realized that this might be categorized as dependencies. I'm familiar with Django but not particularly well-versed in FastAPI's dependencies.

thx

**Comment by yejue** [comment]
Oh, I think i got it

**Comment by zhanymkanov** [comment]
Did you find my [template project](https://github.com/zhanymkanov/fastapi_production_template)?
