### ISSUE TITLE
Pydantic v2 Async field validator

### ISSUE THREAD

**Issue by alikhd1** [zhanymkanov/fastapi-best-practices#49]
is there anyway to call async function in pydantic field validator?

like [this example](https://github.com/zhanymkanov/fastapi-best-practices?tab=readme-ov-file#21-raise-a-valueerror-in-custom-pydantic-validators-if-schema-directly-faces-the-client)? 

i found [this](https://github.com/pydantic/pydantic/issues/857#issuecomment-537570546) on pydantic repo issues

do you have any solution for this?

```python
from pydantic import BaseModel, validator


async def is_admin(id) -> bool:
    # some query to db
    return True

class IsAdminSchema(BaseModel):
    user_id: int
        
    @field_validator('user_id')
    @classmethod
    async def user_id_validator(cls, v: int) -> int:
        if await is_admin(value):
            return v
        raise Forbidden()

```

**Comment by zhanymkanov** [comment]
No. 

Pydantic is a schema validator, not suited for DB models. Do business logic validator in other places.
